### ISSUE TITLE
Fix importing of INDRA dependencies

### ISSUE THREAD

**Issue by csvoss** [csvoss/syndra#20]
This has actually been a problem for a while, but it's more annoying now. I need to figure out the intended way to import INDRA. Fixing this may involve making a pull request to INDRA.

I cannot do something like this:

```
from indra.indra import trips
```

because the first `indra` is not a module (it lacks an `__init__.py`). Even supposing that I fix that, I run into issues where stuff in INDRA assumes that we'll be doing imports a la `import indra.whatever`, which breaks things when I'm instead doing `indra.indra.whatever`.

It would be nice if I could simply fix this by using the inner `indra` subfolder of the outer `indra` folder as my module, but I can't do that because the inner `indra` has dependencies on the folder `data`, which is in the outer `indra` folder. This feels like an abstraction violation, so I'll see if I can fix it.

Also to consider: looking into whether `indra` is pip-installable; then we could get rid of the submodule altogether.

**Comment by bgyori** [comment]
I don't exactly understand the problem but you can certainly do
pip install git+https://github.com/sorgerlab/indra.git

**Comment by bgyori** [comment]
By the way, if INDRA is not installed you can add the outer folder to the PYTHONPATH and then imports work like:
from indra.trips import trips_api 
You should not have to ever write "indra.indra".

**Comment by bgyori** [comment]
Ah, I understand, you are right - the data folder should only be used for "extra" data files and not for actual module dependencies. I will fix this and let you know when it's done.

**Comment by bgyori** [comment]
Okay, moved around a few things so there are no dependencies in data anymore. So this shouldn't problem as of sorgerlab/indra@006ae91
Does this look okay?

**Comment by csvoss** [comment]
Woah, awesome, thank you!

**Comment by csvoss** [comment]
It's working correctly! Thanks for the PYTHONPATH tip, too.
