### ISSUE TITLE
Debug system which should produce phosphorylation rule

### ISSUE THREAD

**Issue by csvoss** [csvoss/syndra#24]
Now that I can pretty-print my z3 models, I see that the following Syndra predicate:

```
ModelHasRule(lambda r: And(
        PregraphHas(r, kinase.labeled(active)),
        PregraphHas(r, substrate),
        PostgraphHas(r, kinase.labeled(active)),
        PostgraphHas(r, substrate.labeled(phosphate)),
)).get_python_model()
```

produces the following model:

```
[Rule({kinase-(active, phosphate) with links to kinase} -> {kinase-(active, phosphate) with links to kinase})]
```

This is in error; the substrate does not become phosphorylated. (Maybe it's incorrectly merging substrate and kinase into the same agent?) Fix this.

**Comment by csvoss** [comment]
Improved! 

```
[Rule({substrate-(active, phosphate) with links to substrate, kinase, kinase-(active, phosphate) with links to substrate, kinase} -> {substrate-(active, phosphate) with links to substrate, kinase, kinase-(active, phosphate) with links to substrate, kinase})]
```

There was a bug in the deciphering of names in the model. Now at least `substrate` and `kinase` are both mentioned, and technically this rule satisfies the Syndra predicate.

**Comment by csvoss** [comment]
Next up: why are there spurious links and spurious agents? And can I come up with Syndra predicates to prevent spurious things in rules?

**Comment by jeanqasaur** [comment]
@csvoss What are examples of spurious links and agents?

## 

Jean Yang
website http://jeanyang.com | twitter http://twitter.com/jeanqasaur
http://people.csail.mit.edu/jeanyang

**Comment by csvoss** [comment]
In the above rule, we have all sorts of unnecessary agents on the LHS and RHS of the rule; this is because I'm not being strict enough about what the rule can contain.

I do notice a quick error I can fix to make that rule more readable, though, which I'll do after lunch.

**Comment by csvoss** [comment]
The error was that too many things were separated by commas, so I made nodes be separated by semicolons and now the notation lets us see what's going on:

```
[Rule({substrate-(active, phosphate) with links to substrate, kinase; kinase-(active, phosphate) with links to substrate, kinase} -> {substrate-(active, phosphate) with links to substrate, kinase; kinase-(active, phosphate) with links to substrate, kinase})]
```
