### ISSUE TITLE
Fix tests to work with slightly-changed API

### ISSUE THREAD

**Issue by csvoss** [csvoss/syndra#31]

**Comment by jeanqasaur** [comment]
Cool! Good work Chelsea. ;) Are the tests working with the Occam's razor
fix now?

## 

Jean Yang
website http://jeanyang.com | twitter http://twitter.com/jeanqasaur
http://people.csail.mit.edu/jeanyang

**Comment by csvoss** [comment]
Now they are!

Commit 8448960689234dc1e9bdeee376ca29d076d95b28
